# Form implementation generated from reading ui file 'C:\Demo\ImageColorPicker\imagecolorpicker\widgets\gradienteditor\gradienteditor.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GradientEditor(object):
    def setupUi(self, GradientEditor):
        GradientEditor.setObjectName("GradientEditor")
        GradientEditor.resize(386, 339)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GradientEditor)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.descriptionLayout = QtWidgets.QVBoxLayout()
        self.descriptionLayout.setSpacing(6)
        self.descriptionLayout.setObjectName("descriptionLayout")
        self.horizontalLayout.addLayout(self.descriptionLayout)
        self.gradientPreview = QtOpenGLWidgets.QOpenGLWidget(parent=GradientEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gradientPreview.sizePolicy().hasHeightForWidth())
        self.gradientPreview.setSizePolicy(sizePolicy)
        self.gradientPreview.setMinimumSize(QtCore.QSize(64, 64))
        self.gradientPreview.setObjectName("gradientPreview")
        self.horizontalLayout.addWidget(self.gradientPreview)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(parent=GradientEditor)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)

        self.retranslateUi(GradientEditor)
        QtCore.QMetaObject.connectSlotsByName(GradientEditor)

    def retranslateUi(self, GradientEditor):
        _translate = QtCore.QCoreApplication.translate
        GradientEditor.setWindowTitle(_translate("GradientEditor", "Form"))
from PyQt6 import QtOpenGLWidgets
